### ISSUE TITLE
Both Reaper pod containers aren't using the same secrets

### ISSUE THREAD

**Issue by adejanovski** [k8ssandra/reaper-operator#85]
**Describe the bug**
When using a predefined secret for jmx and cassandra, the init container and the main container seem to drift away and use different secret references.
The init container seems to get the default secret name that is used when the helm templates autogenerate it while the main container is using the custom secret name.
This cluster was first using autogenerated secrets and later upgraded to use custom secrets.

**Expected behavior**
The secrets used to connect to Cassandra should be the same for both the init and the main container

**Screenshots**

![](https://user-images.githubusercontent.com/5096002/142371269-9063f6e7-c073-4bde-b53d-97b9fb887689.png)

**Environment (please complete the following information):**

* reaper-operator version:
v0.3.3
* Kubernetes version information:
v1.21
* Kubernetes cluster kind:
GKE
* Manifests:

```
  reaper:
    autoschedule: true
    enabled: true
    ingress:
      enabled: false
    image:
      registry: docker.io
      repository: thelastpickle/cassandra-reaper
      tag: 3.0.0
      pullPolicy: IfNotPresent
    cassandraUser:
      username: "reaper"
      secret: "dogfood-reaper-secret"
    jmx:
      username: "reaper"
      secret: "dogfood-reaper-jmx-secret"
```

* Operator logs:

**Additional context**

┆Issue is synchronized with this [Jira Task](https://k8ssandra.atlassian.net/browse/K8SSAND-1059) by [Unito](https://www.unito.io)
┆friendlyId: K8SSAND-1059
┆priority: Medium
